### PR TITLE
Fix a few bugs and add cool things

### PR DESCRIPTION
**Pull request by Stilic**
The commits names literally explain most of the time what I did.

### CODE REVIEW

**Comment by Stilic** [comment]
Hold on
I wanna try to add Actions builds on my phone

**Comment by Stilic** [comment]
yipee now it's done!!
@YoshiCrafter29 if you see this, please, can you merge this or tell me if there's something wrong?

**Review by MemeHoovy — APPROVED** [review]

**Comment by YoshiCrafter29** [comment]
i don't think i'll merge this commit

the issue with is is the syntax "fixing"

i prefer keeping it that way since i have 100% control over it

that pr looked good but im sorry i can't merge it.

**Comment by Stilic** [comment]
> i don't think i'll merge this commit
> 
> the issue with is is the syntax "fixing"
> 
> i prefer keeping it that way since i have 100% control over it
> 
> that pr looked good but im sorry i can't merge it.

thanks for the feedback
i understand about the syntax stuff and i would really remove that, but i can't revert it (i use [this](https://github.com/HaxeCheckstyle/haxe-formatter) to do it)

**Pull request closed without merging**
