### PR TITLE
Note Splashes (from Week 7)

### PR DESCRIPTION
**Pull request by biomseed**
Adds notesplashes, an option to disable notesplashes, and a cancel notesplash function for note hit events. It should be pretty easy to remove the weird formatting on the imports, unless you want to keep it. The code except for the options is from [the 0.2.8 decompilation](https://github.com/AngelDTF/FNF-NewgroundsPort), of course modified to make it fit with the engine

### CODE REVIEW

**Comment by biomseed** [comment]
I've still got one change to make. Give me a sec.

**Comment by biomseed** [comment]
Alright. You can merge it now.

**Comment by biomseed** [comment]
yoshi

**Comment by biomseed** [comment]
yoshi

**Comment by biomseed** [comment]
it still works

**Comment by biomseed** [comment]
if there's something you don't like about it just tell me

**Comment by YoshiCrafter29** [comment]
I'm sorry, i'm closing this PR.

I prefer coding things such as note splashes myself since there's a lot of factors to take in count, which your PR sadly doesn't implement.

You should prob turn this into a script tho, its sick

**Comment by biomseed** [comment]
> I'm sorry, i'm closing this PR.
> 
> I prefer coding things such as note splashes myself since there's a lot of factors to take in count, which your PR sadly doesn't implement.
> 
> You should prob turn this into a script tho, its sick

thank you

**Pull request closed without merging**
