### PR TITLE
fix

### PR DESCRIPTION
**Pull request by Goofgoof43**
.

### CODE REVIEW

**Review by FoxelTheFennic — APPROVED** [review]
(in the future please make your pull request names more descriptive then just "fix" LMAO)

**Comment by Goofgoof43** [comment]
sorry just when i make it late at night im not thinking much

**Comment by YoshiCrafter29** [comment]
Latest folder was here for Baldi's Basics in Funkin' devs who couldn't compile the engine when it was private.
Since the Baldi Funkin repo now contains the latest Codename Build, the latest folder is totally useless.
Closing.

**Comment by Goofgoof43** [comment]
Well for me it compiles stuff into the latest folder

**Pull request closed without merging**
